<<<<<<<< HEAD:.github/workflows/main.yml
name: main
========

name: version1.3
>>>>>>>> a446dfb1bda291d50c69876fbd1ddc807c432d24:.github/workflows/version1.3.yml

on:
  workflow_dispatch

jobs:
  ssh-deploy:
    runs-on: [self-hosted, shopdesk]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH into server and run commands
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_IP: ${{ secrets.SSH_IP }}
          REPO_URL: ${{ secrets.REPO_URL }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USERNAME@$SSH_IP" "
            if [ -d 'shopdesk-fe' ]; then
              cd shopdesk-fe &&
              echo 'Pulling latest changes...' &&
<<<<<<<< HEAD:.github/workflows/main.yml
              git checkout main &&
              git reset --hard HEAD &&
              git pull origin main || { echo 'Git pull failed'; git status; exit 1; } &&
              pm2 delete shopdesk || true &&  # Gracefully handle missing process
              echo '$SSH_PASSWORD' | sudo -S fuser -k 7777/tcp || echo 'No process found on port 7777' &&
              bun install || { echo 'bun install failed'; exit 1; } &&
              bun run build || { echo 'bun run build failed'; exit 1; } &&
              pm2 start \"bun run start\" --name \"shopdesk\" --watch || { echo 'pm2 start failed'; exit 1; }
            else
              git clone $REPO_URL || { echo 'Git clone failed'; exit 1; } &&
              cd $(basename $REPO_URL .git) &&
              git checkout main &&
              pm2 delete shopdesk || true &&  # Gracefully handle missing process
              echo '$SSH_PASSWORD' | sudo -S fuser -k 7777/tcp || echo 'No process found on port 7777' &&
========
              git checkout version1.3 &&
              git reset --hard HEAD &&
              git pull origin version1.3 || { echo 'Git pull failed'; git status; exit 1; } &&
              pm2 delete shopdesk || true &&  # Gracefully handle missing process
              bun install || { echo 'bun install failed'; exit 1; } &&
              bun run build || { echo 'bun run build failed'; exit 1; } &&
              pm2 start \"bun run start\" --name \"shopdesk\" --watch || { echo 'pm2 start failed'; exit 1; } &&
              pm2 save
            else
              git clone $REPO_URL || { echo 'Git clone failed'; exit 1; } &&
              cd $(basename $REPO_URL .git) &&
              git checkout version1.3 &&
              echo 'Checked out to Version 1.3' &&
>>>>>>>> a446dfb1bda291d50c69876fbd1ddc807c432d24:.github/workflows/version1.3.yml
              echo 'Running bun install.....' &&
              bun install || { echo 'bun install failed'; exit 1; } &&
              echo 'Running bun run build.....' &&
              bun run build || { echo 'bun run build failed'; exit 1; } &&
              echo 'Running bun start.....' &&
              pm2 start \"bun run start\" --name \"shopdesk\" --watch --ignore-watch \"node_modules logs\"
            fi
          "
